/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modele;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.sql.DriverManager;



/**
 *
 * @author Client
 */
public class Contrat extends javax.swing.JFrame {
    Connection con;
PreparedStatement pst ;
ResultSet rs;
    /**
     * Creates new form Contrat
     */
    public Contrat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeltitre = new javax.swing.JLabel();
        jLabelnumclient = new javax.swing.JLabel();
        jLabelnumcontrat = new javax.swing.JLabel();
        jLabeldate = new javax.swing.JLabel();
        jLabelnummat = new javax.swing.JLabel();
        jTextFieldnummat = new javax.swing.JTextField();
        jTextFieldnumcontrat = new javax.swing.JTextField();
        jTextFieldnumclient = new javax.swing.JTextField();
        jTextFielddate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelbuttonsss = new javax.swing.JPanel();
        jButtonexit = new javax.swing.JButton();
        jButtonajouter = new javax.swing.JButton();
        jButtonmodifier = new javax.swing.JButton();
        jButtonsupprimer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabeltitre.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabeltitre.setForeground(new java.awt.Color(255, 153, 153));
        jLabeltitre.setText("fiche contrat");

        jLabelnumclient.setText("numero client");

        jLabelnumcontrat.setText("numero contrat");

        jLabeldate.setText("date");

        jLabelnummat.setText("numero matricule");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "numcont", "nummat", "numclient", "date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonexit.setText("fermer");
        jButtonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexitActionPerformed(evt);
            }
        });

        jButtonajouter.setText("ajouter");
        jButtonajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonajouterActionPerformed(evt);
            }
        });

        jButtonmodifier.setText("modifier");
        jButtonmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmodifierActionPerformed(evt);
            }
        });

        jButtonsupprimer.setText("supprimer");
        jButtonsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelbuttonsssLayout = new javax.swing.GroupLayout(jPanelbuttonsss);
        jPanelbuttonsss.setLayout(jPanelbuttonsssLayout);
        jPanelbuttonsssLayout.setHorizontalGroup(
            jPanelbuttonsssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbuttonsssLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelbuttonsssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonexit, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelbuttonsssLayout.setVerticalGroup(
            jPanelbuttonsssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelbuttonsssLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonexit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelnumclient, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldnumclient, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabeldate, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFielddate, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelnummat, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldnummat, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabeltitre, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelnumcontrat, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldnumcontrat, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(116, 116, 116)
                        .addComponent(jPanelbuttonsss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabeltitre, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelnumcontrat, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldnumcontrat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelnummat, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldnummat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelnumclient, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldnumclient, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeldate, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFielddate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanelbuttonsss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexitActionPerformed
        Contrat.super.dispose();
        MenuePrincipale men=new MenuePrincipale ();
        men.setVisible(true);
    }//GEN-LAST:event_jButtonexitActionPerformed

    private void jButtonajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonajouterActionPerformed
try{  
Class.forName("com.mysql.jdbc.Driver");
con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/voiture?autoReconnect=true&useSSL=false","root","admin");
String sql= "insert into contrat(numcont,nummat,numclient,date)values (?,?,?,?) ";
pst=con.prepareStatement (sql);
pst.setString(1,jTextFieldnumcontrat.getText());
pst.setString(2,jTextFieldnummat.getText());
pst.setString(3,jTextFieldnumclient.getText());
pst.setString(4,jTextFielddate.getText());
pst.execute();
con.close();
JOptionPane.showMessageDialog(null, "Contrat ajouter");
}catch (Exception e){
JOptionPane.showMessageDialog(null, "erreur ici" +e.getMessage());}
    }//GEN-LAST:event_jButtonajouterActionPerformed

    private void jButtonsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsupprimerActionPerformed
try{
Class.forName("com.mysql.jdbc.Driver");
con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/voiture?autoReconnect=true&useSSL=false","root","admin");
String sql= "DELETE FROM contrat WHERE numcont=?";
pst=con.prepareStatement (sql);
pst.setString(1,jTextFieldnumcontrat.getText());
int rowsDeleted = pst.executeUpdate();
con.close();
if (rowsDeleted > 0) {
JOptionPane.showMessageDialog(null, "La ligne a été supprimée avec succès.");
} else {
JOptionPane.showMessageDialog(null, "Aucune ligne n'a été supprimée.");
}
} catch (Exception e) {
JOptionPane.showMessageDialog(null, "erreur ici" +e.getMessage());
}

    }//GEN-LAST:event_jButtonsupprimerActionPerformed

    private void jButtonmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmodifierActionPerformed
try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/voiture?autoReconnect=true&useSSL=false", "root", "admin");
    String sql = "UPDATE contrat SET nummat=?, numclient=?, date=? WHERE numcont=?";
    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, jTextFieldnummat.getText());
    pst.setString(2, jTextFieldnumclient.getText());
    pst.setString(3, jTextFielddate.getText());
    pst.setString(4, jTextFieldnumcontrat.getText());
    int rowsUpdated = pst.executeUpdate();
    con.close();
    if (rowsUpdated > 0) {
        JOptionPane.showMessageDialog(null, "La ligne a été modifiée avec succès.");
    } else {
        JOptionPane.showMessageDialog(null, "Aucune ligne n'a été modifiée.");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "erreur ici" + e.getMessage());
}
    }//GEN-LAST:event_jButtonmodifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contrat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contrat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contrat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contrat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contrat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonajouter;
    private javax.swing.JButton jButtonexit;
    private javax.swing.JButton jButtonmodifier;
    private javax.swing.JButton jButtonsupprimer;
    private javax.swing.JLabel jLabeldate;
    private javax.swing.JLabel jLabelnumclient;
    private javax.swing.JLabel jLabelnumcontrat;
    private javax.swing.JLabel jLabelnummat;
    private javax.swing.JLabel jLabeltitre;
    private javax.swing.JPanel jPanelbuttonsss;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFielddate;
    private javax.swing.JTextField jTextFieldnumclient;
    private javax.swing.JTextField jTextFieldnumcontrat;
    private javax.swing.JTextField jTextFieldnummat;
    // End of variables declaration//GEN-END:variables
}

