/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modele;

/**
 *
 * @author Client
 */
public class MenuePrincipale extends javax.swing.JFrame {

    /**
     * Creates new form MenuePrincipale
     */
    public MenuePrincipale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1font = new javax.swing.JPanel();
        jLabeltitre = new javax.swing.JLabel();
        jButtonclient = new javax.swing.JButton();
        jButtoncontrat = new javax.swing.JButton();
        jButtonvéhicule = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1font.setBackground(new java.awt.Color(102, 153, 255));

        jLabeltitre.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 48)); // NOI18N
        jLabeltitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeltitre.setText("gestion de location des voitures ");
        jLabeltitre.setPreferredSize(new java.awt.Dimension(16, 53));

        jButtonclient.setBackground(new java.awt.Color(255, 153, 51));
        jButtonclient.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jButtonclient.setText("gestion client");
        jButtonclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclientActionPerformed(evt);
            }
        });

        jButtoncontrat.setBackground(new java.awt.Color(255, 153, 51));
        jButtoncontrat.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jButtoncontrat.setText("gestion contrat");
        jButtoncontrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncontratActionPerformed(evt);
            }
        });

        jButtonvéhicule.setBackground(new java.awt.Color(255, 153, 51));
        jButtonvéhicule.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jButtonvéhicule.setText("gestion véhicule");
        jButtonvéhicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonvéhiculeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setText("merci d'avoir utiliser notre application ........");

        javax.swing.GroupLayout jPanel1fontLayout = new javax.swing.GroupLayout(jPanel1font);
        jPanel1font.setLayout(jPanel1fontLayout);
        jPanel1fontLayout.setHorizontalGroup(
            jPanel1fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1fontLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addGroup(jPanel1fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1fontLayout.createSequentialGroup()
                        .addComponent(jButtoncontrat, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(jPanel1fontLayout.createSequentialGroup()
                        .addGroup(jPanel1fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonvéhicule, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonclient, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1fontLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabeltitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1fontLayout.setVerticalGroup(
            jPanel1fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1fontLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabeltitre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonclient, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1fontLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1fontLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButtonvéhicule, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jButtoncontrat, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1font, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1font, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1080, 482);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclientActionPerformed
       MenuePrincipale.super.dispose();
       Clients c1=new Clients();
       c1.setVisible(true);
    }//GEN-LAST:event_jButtonclientActionPerformed

    private void jButtonvéhiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonvéhiculeActionPerformed
        MenuePrincipale.super.dispose();
       Vehicule v1=new Vehicule();
       v1.setVisible(true);
    }//GEN-LAST:event_jButtonvéhiculeActionPerformed

    private void jButtoncontratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncontratActionPerformed
         MenuePrincipale.super.dispose();
       Contrat c2=new Contrat();
       c2.setVisible(true);
    }//GEN-LAST:event_jButtoncontratActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonclient;
    private javax.swing.JButton jButtoncontrat;
    private javax.swing.JButton jButtonvéhicule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabeltitre;
    private javax.swing.JPanel jPanel1font;
    // End of variables declaration//GEN-END:variables
}
